version: "3"

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/live_chat
        depends_on:
            - db
        ports:
            - "8000:8000"
        restart: on-failure
        container_name: django
    db:
        image: postgres
        environment:
            POSTGRES_DB: dev
            POSTGRES_PASSWORD: docker
            POSTGRES_USER: docker
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - web

volumes:
  postgres_data: